### ISSUE TITLE
Recalls is a string and not an integer

### ISSUE THREAD

**Issue by metbril** [eelcohn/home-assistant-rdw#10]
See #7 and #8.

**Update:**
This is an issue, for example, when you want to use the number of recalls as a trigger in an automation (greather than 0) or in an `entity-filter` case. I use the latter to hide the entity unless there actually is a recall.

**Comment by metbril** [comment]
I think a simple solution is to specify a default `unit_of_measurement` of `"recalls"`. This way HA will interpret the state as a number (also in history).

**Comment by eelcohn** [comment]
This is fixed in the latest release of the RDW platform (v2.9.0). I've just pushed it to the github repository.
