### ISSUE TITLE
Can't set up

### ISSUE THREAD

**Issue by golles** [eelcohn/home-assistant-rdw#11]
Hi,

After setting up the custom component and the config, I'm not getting any sensors and after a while I see issues in the log:

```
Log Details (ERROR)
Tue Feb 25 2020 17:20:18 GMT+0100 (Midden-Europese standaardtijd)
'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 123, in async_handle_update_service
    for entity in call.data[ATTR_ENTITY_ID]
KeyError: 'entity_id'
```
and
```
Log Details (ERROR)
Tue Feb 25 2020 17:18:46 GMT+0100 (Midden-Europese standaardtijd)
http://HASS/frontend_latest/chunk.a43c77da5c1bf5fdcb4f.js:518:874 Uncaught TypeError: Cannot read property 'state' of undefined
```

I've verified with my plate number that it returns details from the url: https://opendata.rdw.nl/resource/m9d7-ebf2.json?kenteken=

Bedankt!

**Comment by eelcohn** [comment]
Hi golles!
Interesting, I've never seen that type of error before. Can you post the part of your `configuration.yaml` related to the RDW component?

**Comment by eelcohn** [comment]
I've published v2.9.1 of the RDW entity. Please update your config to the latest version and see if the problem still exists.

**Comment by golles** [comment]
Hi, I was away for a while and couldn't test. I'll update now and let you know if I see this again, thank you!

**Comment by golles** [comment]
I was able to set it up now, I do see this entry in my log. However, I think I can ignore it?
`Requests made without an app_token will be subject to strict throttling limits.
`

**Comment by eelcohn** [comment]
Glad to hear that you're able to set it up correctly!

Yes you can ignore that warning. That warning comes from the [`sodapy` library](https://pypi.org/project/sodapy/). I'll add some info about that later on in the FAQ.
