### ISSUE TITLE
Requests made without an app_token will be subject to strict throttling limits. 

### ISSUE THREAD

**Issue by TheRedBull205** [eelcohn/home-assistant-rdw#17]
Currently getting the next error with using the latest version:

I don't see yet how to get a token that should probably come from:
https://opendata.rdw.nl/

But there is currently also not an option in the configuration to insert this token. Or is this supported in the dashboard of HA?

```
Log Details (WARNING)
Logger: root
Source: custom_components/rdw/__init__.py:185
First occurred: 11:30:51 PM (2 occurrences)
Last logged: 11:30:52 PM 
Requests made without an app_token will be subject to strict throttling limits. 
```

**Comment by eelcohn** [comment]
Should be fixed in v2.9.4
