### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by TheRedBull205** [eelcohn/home-assistant-rdw#18]
Since Home Assistant 0.109.0:

- Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for rdw doing I/O at custom_components/rdw/__init__.py, line 211: kenteken=self._plate
- Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for rdw doing I/O at custom_components/rdw/__init__.py, line 225: kenteken=self._plate

**Comment by eelcohn** [comment]
Thank you for reporting this. I'll have to look into this to upgrade the code to be compatible with Home Assistant core v0.109.0 and upwards.

**Comment by eelcohn** [comment]
Should be fixed in v2.9.5
