### ISSUE TITLE
Discovery causing new integrations to be added multiple times

### ISSUE THREAD

**Issue by syphernl** [eelcohn/home-assistant-rdw#22]
After updating to the latest version of the sensor and HASS I keep on getting notifications that "new devices have been discovered". The integrations page now shows 3 RDW instances, even though I have only one car configured.

**Comment by eelcohn** [comment]
Sorry about this, I introduced a bug in v2.9.2. It should be fixed now in v2.9.3.

**Comment by syphernl** [comment]
It is still creating a new instance when I reboot.

**Comment by eelcohn** [comment]
Hi @syphernl, this bug is indeed still present, see also #21 . I've been able to replicate the problem in a test environment and I'm working on a solution.

**Comment by eelcohn** [comment]
Should be fixed in the latest release (v2.9.6). Please feel free to re-open this issue if you still experience the same problem.
