### ISSUE TITLE
Error handling on unregistered license plate IDs

### ISSUE THREAD

**Issue by eelcohn** [eelcohn/home-assistant-rdw#30]
From the community.home-assistant.io site:

I have setup rdw but it don’t work.

My conf:
rdw:

    plate: 0xxx00
    name: “BMW”
    binary_sensors:
        insured
        sensors:
        expdate
        recall
    plate: 00xxxx
    name: “C1”
    binary_sensors:
        insured
        sensors:
        expdate
        recall

Error:
Logboekdetails (ERROR)

Logger: homeassistant.config_entries
Source: custom_components/rdw/init.py:275
First occurred: 19:31:29 (2 occurrences)
Last logged: 19:31:29

Error setting up entry C1 (configuration.yaml) for rdw
Error setting up entry BMW (configuration.yaml) for rdw

Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/config_entries.py”, line 217, in async_setup
hass, self
File “/config/custom_components/rdw/init.py”, line 107, in async_setup_entry
if not await rdw.async_update():
File “/config/custom_components/rdw/init.py”, line 275, in async_update
raise RDWEntity.NotRegistered
custom_components.rdw.RDWEntity.NotRegistered

**Comment by indykoning** [comment]
I've got the same issue, it is registered and worked on a previous version (afraid i don't know what version but it didn't have the config flow yet and was set up as a sensor instead of a platform)

**Comment by eelcohn** [comment]
The RDW service was integrated in Home Assistant 2021.12, which makes my custom RDW integration obsolete. Please remove the custom RDW integration, and use the built-in RDW integration.
