### ISSUE TITLE
Recalls numeric with unit of measurement

### ISSUE THREAD

**Issue by metbril** [eelcohn/home-assistant-rdw#33]
Running latest version of everything ...

The recalls sensor give back a string value without unit of measurement. It should give back an integer with a unit of measurement like `recalls`.

**Comment by metbril** [comment]
I did some tests and adding a default unit should be sufficient.

**Comment by eelcohn** [comment]
The RDW service was integrated in Home Assistant 2021.12, which makes my custom RDW integration obsolete. Please remove the custom RDW integration, and use the built-in RDW integration.
