### ISSUE TITLE
Binary sensor value

### ISSUE THREAD

**Issue by metbril** [eelcohn/home-assistant-rdw#34]
The values `True` and `False` do not work properly with device classes. Instead `on` or `off` could be used (lowercase), or constants.

https://github.com/eelcohn/home-assistant-rdw/blob/8a44d29b54b6557c27f74da47ad2ab7328f59e1e/binary_sensor.py#L148

**Comment by metbril** [comment]
The current values are hard coded text, and are NOT translated to localized strings. `Safe/Unsafe` should be translated to `Veilig/Onveilig` in Dutch.

**Comment by eelcohn** [comment]
The RDW service was integrated in Home Assistant 2021.12, which makes my custom RDW integration obsolete. Please remove the custom RDW integration, and use the built-in RDW integration.
