### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dennidoubles** [eelcohn/home-assistant-rdw#39]
Not sure if I can leave this question here, but let me try.
I've installed RDW and now I want to add it. So, I go to Integrations, search for RDW and click it.

A pop-up appears, but without explanation what to fill in. 

So, can you help? What to fill in? It is an empty popup, but I have to fill something in before I can submit...

Thanks a lot for your quick reponse!
![rdw](https://user-images.githubusercontent.com/71798417/113353557-256ba880-933e-11eb-9a52-895057693e6a.JPG)

**Comment by syphernl** [comment]
@dennidoubles That field expects a license plate. Odd, I see a label just fine here.

**Comment by dennidoubles** [comment]
> @dennidoubles That field expects a license plate. Odd, I see a label just fine here.

Thanks for replying syphernl. I expected that, but that gives me nothing more than errors.
Don't understand what's wrong, I'll try again taking the steps needed to have RDW added as an integration then.

If you have any other advice, please do so.

Thanks!

![image](https://user-images.githubusercontent.com/71798417/113993137-6854e100-9854-11eb-87d5-6faa4424a6c6.png)

**Comment by syphernl** [comment]
That seems to be the similar to a different issue: https://github.com/eelcohn/home-assistant-rdw/issues/32

**Comment by dennidoubles** [comment]
Looks like it indeed, but there isn't a solution on this isssue mentioned last september?
Then I think it would be best, to leave it as it is, because the integration isn't working, or do you suggest something else?

Thanks again

**Comment by syphernl** [comment]
I can't seem to get it to work with my new car either unfortunately. 😢

**Comment by dennidoubles** [comment]
😕 Okay...well, I guess that's it then 🤷
Too bad 😓

**Comment by groenmarsmannetje** [comment]
I am also not able to install it anymore after I updated to latest version after a long time. Seems that this integration is broken. Hopefully it will work again when it becomes available in HA or HACS. For now I think I will remove it from my HA.

**Comment by eelcohn** [comment]
Sorry for the late response, I've been quite busy with real-life stuff for the past couple of months, so GitHub wasn't on my priority list... My own HomeAssistant setup has broken the RDW component since update 2021.2. I'm gonna try to find a fix in the next few days.

**Comment by dennidoubles** [comment]
Perfect @eelcohn , very much appreciated!
And you're right...first things first!
Looking forward to your fix , whenever you're able to👌

**Comment by remyderuysscher** [comment]
Any news yet?

**Comment by groenmarsmannetje** [comment]
> Any news yet?

Seems that this integration has been abondened. But I can confirm that the workaround by installing version 2.9.6 with adding version number in manifiest file as described here #32 does work for me. So it shouldn't seem to be so difficult to fix as it must be caused by a change between these 2 versions.

**Comment by TheRedBull205** [comment]
RDW has been build into HA version: 2021.12
https://rc--home-assistant-docs.netlify.app/integrations/rdw/
Beta release notes: https://rc--home-assistant-docs.netlify.app/blog/

(THANKS Frenck!!)

**Comment by eelcohn** [comment]
The RDW service was integrated in Home Assistant 2021.12, which makes my custom RDW integration obsolete. Please remove the custom RDW integration, and use the built-in RDW integration.
