### ISSUE TITLE
Intergration doesn't work anymore after update 2021.6.0

### ISSUE THREAD

**Issue by jobvk** [eelcohn/home-assistant-rdw#41]
#### Versions
_RDW component version: ```2.9.7```
_Home Assistant version: ```2021.6.0```
_Home Assistant platform: ```supervisor-2021.05.4``` | ```Home Assistant OS 5.13```

#### Expected behavior
Tell us what should happen
Integration should load normal.

#### Actual behavior
Tell us what happens instead
Getting erros when starting Integration.

#### Error log
```
Error 1:
The system cannot restart because the configuration is not valid: Component error: rdw - Integration 'rdw' not found.

Error 2:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: rdw - Integration 'rdw' not found.

**Comment by patrickdev19** [comment]
Just add version property to manifest.json since integrations without are blocked by version 2021.6.0 https://github.com/home-assistant/core/pull/49916

**Comment by eelcohn** [comment]
Interesting... The `version` key is already present in `manifest.json`. Perhaps it's another change in the manifest.json from the past 6-9 months.

**Comment by SamKr** [comment]
@jobvk: same here, but that's resolved in the latest version

@eelcohn: older versions didn't, I had the same problem as jobvk - manifest didn't contain version, but oddly enough, home assistant didn't give the 'version missing' warning it did with other components. However, after updating to the latest version the problem went away.

**Comment by jobvk** [comment]
Yes it is working again now.
I will therefore close the issue now.
