### ISSUE TITLE
APK date is a string

### ISSUE THREAD

**Issue by metbril** [eelcohn/home-assistant-rdw#8]
The `expired` sensor is a formatted string. It would be better/best if it is an actual datetime type sensor. It can then be formatted according to the user's preferences and can be used more easily in calculations.

Compare with the `time_date` sensor:

https://www.home-assistant.io/integrations/time_date/

**Comment by eelcohn** [comment]
Agreed. Do you know where the default datetime sensor type and/or format is defined?

Edit: disregard that, already found it.

**Comment by eelcohn** [comment]
This is fixed in the latest release of the RDW platform (v2.9.0). I've just pushed it to the github repository.
